### ISSUE TITLE
Painkiller

### ISSUE THREAD

**Issue by eyekelly** [wakaleo/game-of-life#194]
Can you please update this so its not so painful to work with? all I get is this. 

Started by user ian kelly
Building in workspace /var/lib/jenkins/workspace/game-of-life-default
Cloning the remote Git repository
Cloning repository https://github.com/eyekelly/game-of-life.git
 > git init /var/lib/jenkins/workspace/game-of-life-default # timeout=10
Fetching upstream changes from https://github.com/eyekelly/game-of-life.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/eyekelly/game-of-life.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/eyekelly/game-of-life.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/eyekelly/game-of-life.git # timeout=10
Fetching upstream changes from https://github.com/eyekelly/game-of-life.git
 > git fetch --tags --progress https://github.com/eyekelly/game-of-life.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision d97e493e7507a80bcc427697a5daf99c7e9418fd (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d97e493e7507a80bcc427697a5daf99c7e9418fd
Commit message: "Merge pull request #2 from eyekelly/revert-1-surefire-version2201"
 > git rev-list d97e493e7507a80bcc427697a5daf99c7e9418fd # timeout=10
[game-of-life-default] $ /usr/local/apache-maven-3.5.2/bin/mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.wakaleo.gameoflife:gameoflife-build:jar:1.0-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.wakaleo.gameoflife:gameoflife-core:jar:1.0-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.wakaleo.gameoflife:gameoflife-web:war:1.0-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.wakaleo.gameoflife:gameoflife:pom:1.0-SNAPSHOT
[WARNING] Reporting configuration should be done in <reporting> section, not in maven-site-plugin <configuration> as reportPlugins parameter. @ line 302, column 40
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] gameoflife
[INFO] gameoflife-build
[INFO] gameoflife-core
[INFO] gameoflife-web
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building gameoflife 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ gameoflife ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-versions) @ gameoflife ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:prepare-agent (jacoco-initialize) @ gameoflife ---
[INFO] argLine set to -javaagent:/var/lib/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/var/lib/jenkins/workspace/game-of-life-default/target/jacoco.exec
[INFO] 
[INFO] --- maven-surefire-plugin:2.11:test (unit-tests) @ gameoflife ---
[INFO] No tests to run.
[INFO] Surefire report directory: /var/lib/jenkins/workspace/game-of-life-default/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_e6e56f0.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_e6e56f0.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:1956)
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1:  3316 Aborted                 (core dumped) /var/lib/jenkins/tools/hudson.model.JDK/java/bin/java -javaagent:/var/lib/jenkins/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/var/lib/jenkins/workspace/game-of-life-default/target/jacoco.exec -jar /var/lib/jenkins/workspace/game-of-life-default/target/surefire/surefirebooter5661336041227364955.jar /var/lib/jenkins/workspace/game-of-life-default/target/surefire/surefire17921956382707181233tmp /var/lib/jenkins/workspace/game-of-life-default/target/surefire/surefire10751138448148473142tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gameoflife ......................................... FAILURE [  2.704 s]
[INFO] gameoflife-build ................................... SKIPPED
[INFO] gameoflife-core .................................... SKIPPED
[INFO] gameoflife-web ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.429 s
[INFO] Finished at: 2017-12-04T15:54:50Z
[INFO] Final Memory: 12M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.11:test (unit-tests) on project gameoflife: Error occured in starting fork, check output in log -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Build step 'Invoke top-level Maven targets' marked build as failure
Archiving artifacts
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Finished: FAILURE

**Comment by arcturus140** [comment]
@eyekelly it would be helpful to know your java version.
