### ISSUE TITLE
Game of life not building in Jenkins, (error occured in starting fork)

### ISSUE THREAD

**Issue by murt30** [wakaleo/game-of-life#325]
T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_e6e56f0.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_e6e56f0.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:1999)
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.11:test (unit-tests) on project gameoflife: Error occured in starting fork, check output in log -> [Help 1]

**Comment by ag90786** [comment]
change jacoco version to 0.8.2 in main pom.xml file at 2 places

**Comment by murt30** [comment]
Thanks, I'll try that.
Murt

**Comment by mahak24342** [comment]
please assign me this issue

**Comment by Jkudjo** [comment]
@murt30, did @ag90786  suggestion work for you?

**Comment by basket-random-games** [comment]
Is there a known workaround to prevent JaCoCo from instrumenting system classes like UUID?

Could this be related to the JaCoCo version or the Maven plugin version being used? (Currently using maven-surefire-plugin:2.11)

Should I update JaCoCo or modify agent options (like excludes) to skip JDK/internal classes?

**Comment by Eng-Boy** [comment]
我登陆邮箱的时间一年之中屈指可数啊，所以...
