### ISSUE TITLE
Java Doc generation failing

### ISSUE THREAD

**Issue by edanian** [wakaleo/game-of-life#37]
Hi,

I followed the instructions on page 33-34 to generate Javadocs. The Javadocs for gameoflife-core are generated, but now the buildflow fails due to an error with gameoflife-web. Any hints on what the problem could be?

[INFO] --- maven-war-plugin:2.1.1:war (default-war) @ gameoflife-web ---
[INFO] Packaging webapp
[INFO] Assembling webapp [gameoflife-web] in [C:\Program Files (x86)\Jenkins\workspace\gameoflife-default\gameoflife-web\target\gameoflife]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Program Files (x86)\Jenkins\workspace\gameoflife-default\gameoflife-web\src\main\webapp]
[INFO] Webapp assembled in [604 msecs]
[INFO] Building war: C:\Program Files (x86)\Jenkins\workspace\gameoflife-default\gameoflife-web\target\gameoflife.war
[WARNING] Warning: selected war files include a WEB-INF/web.xml which will be ignored 
(webxml attribute is missing from war task, or ignoreWebxml attribute is specified as 'true')
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gameoflife ......................................... SUCCESS [  3.782 s]
[INFO] gameoflife-build ................................... SUCCESS [  1.830 s]
[INFO] gameoflife-core .................................... SUCCESS [  8.026 s]
[INFO] gameoflife-web ..................................... SUCCESS [  5.022 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.200 s
[INFO] Finished at: 2015-02-17T16:30:10+01:00
[INFO] Final Memory: 26M/309M
[INFO] ------------------------------------------------------------------------
[gameoflife-default] $ mvn.bat javadoc:javadoc
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: Cannot run program "mvn.bat" (in directory "C:\Program Files (x86)\Jenkins\workspace\gameoflife-default"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$ProcStarter.join(Launcher.java:388)
	at hudson.tasks.Maven.perform(Maven.java:328)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1718)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 16 more
Build step 'Invoke top-level Maven targets' marked build as failure
Recording test results
Publishing Javadoc
Archiving artifacts
Finished: FAILURE

BR Daniel

**Comment by edanian** [comment]
Hi again,

After updating the Maven plugin I now get this error instead:

[INFO] ------------------------------------------------------------------------
[INFO] Building gameoflife-web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-javadoc-plugin:2.10.1:javadoc (default-cli) > generate-sources @ gameoflife-web >>>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gameoflife ......................................... SUCCESS [  1.879 s]
[INFO] gameoflife-build ................................... SUCCESS [  0.070 s]
[INFO] gameoflife-core .................................... SUCCESS [  2.778 s]
[INFO] gameoflife-web ..................................... FAILURE [  0.170 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.982 s
[INFO] Finished at: 2015-02-18T09:33:40+01:00
[INFO] Final Memory: 17M/159M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gameoflife-web: Could not resolve dependencies for project com.wakaleo.gameoflife:gameoflife-web:war:1.0-SNAPSHOT: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gameoflife-web
Build step 'Invoke top-level Maven targets' marked build as failure
Recording test results
Archiving artifacts
Publishing Javadoc
Finished: FAILURE

I hope someone have a hint on how to solve this.

BR Daniel

**Comment by jeromeshi** [comment]
just change clean package to clean install is enough.

**Comment by edanian** [comment]
Thanks! I will try that.
