### ISSUE TITLE
game-of-life maven script not working - dependency failures

### ISSUE THREAD

**Issue by quux00** [wakaleo/game-of-life#4]
I am trying to go through chapter 2 of the Jenkins Definitive Guide book, but I am getting errors with the maven build.  First, I am using java 1.6.0_22 and maven 3.0.3 on Ubuntu Linux.  The maven builds fail both in Jenkins and when I run it on the command line directly.  I have encountered two errors, one I worked around and another that I don't know how to fix.  Currently, it is breaking when I run the javadoc:javadoc target.  I don't know much about maven, so I'm needing help to progress with the book.
### First problem - maven dependency errors for "clean package"

I won't copy the full error message as it is similar to the second problem, but it couldn't resolve dependencies having to do with com.wakaleo.gameoflife.  When I looked at where it was trying to pull from, it looked like maybe you had changed the wakaleo maven url, so changing the pom.xml file to the text below fixed it ("mvn clean package" finally worked and all tests passed, etc.) .

```
<repositories>
  <repository>
    <id>wakaleo-releases</id>
    <name>Wakaleo Releases</name>
    <url>http://www.wakaleo.com/maven/repos/</url>
  </repository>
 <repository>
    <id>wakaleo-releases-2</id>
    <name>Wakaleo Releases 2</name>
    <url>http://maven.wakaleo.com/releases/</url>
 </repository>
</repositories>
```
### Second problem - maven dependency errors for "javadoc:javadoc"

Using the same pom.xml above, I now cannot get the javadoc:javadoc target to build.  Here is the error message:
    [INFO] >>> maven-javadoc-plugin:2.8:javadoc (default-cli) @ gameoflife-webservice >>>
    [INFO] 
    [INFO] <<< maven-javadoc-plugin:2.8:javadoc (default-cli) @ gameoflife-webservice <<<
    [DEBUG] Could not find metadata com.wakaleo.gameoflife:gameoflife-core:0.7.47-SNAPSHOT/maven-metadata.xml in local (/home/midpeter444/.m2/repository)
    [DEBUG] com.wakaleo.gameoflife:gameoflife-webservice:jar:0.7.47-SNAPSHOT
    [DEBUG]    com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT:compile
    [DEBUG]    commons-lang:commons-lang:jar:2.5:compile
    [DEBUG]    junit:junit:jar:4.8.2:test
    [DEBUG]    org.hamcrest:hamcrest-all:jar:1.1:test
    [DEBUG] Could not find metadata com.wakaleo.gameoflife:gameoflife-core:0.7.47-SNAPSHOT/maven-metadata.xml in local (/home/midpeter444/.m2/repository)
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] gameoflife ........................................ SUCCESS [2.517s]
    [INFO] gameoflife-build .................................. SUCCESS [1.411s]
    [INFO] gameoflife-core ................................... SUCCESS [3.590s]
    [INFO] gameoflife-webservice ............................. FAILURE [1.391s]
    [INFO] gameoflife-web .................................... SKIPPED
    [INFO] gameoflife-cli .................................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 11.799s
    [INFO] Finished at: Fri Sep 09 18:33:04 EDT 2011
    [INFO] Final Memory: 10M/125M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project gameoflife-webservice: Could not resolve dependencies for project com.wakaleo.gameoflife:gameoflife-webservice:jar:0.7.47-SNAPSHOT: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project gameoflife-webservice: Could not resolve dependencies for project com.wakaleo.gameoflife:gameoflife-webservice:jar:0.7.47-SNAPSHOT: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:196)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:108)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
    Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.wakaleo.gameoflife:gameoflife-webservice:jar:0.7.47-SNAPSHOT: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:170)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:171)
        ... 22 more
    Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:412)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:164)
        ... 23 more
    Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:541)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:220)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:395)
        ... 24 more
    Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.wakaleo.gameoflife:gameoflife-core:jar:0.7.47-SNAPSHOT
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:531)
        ... 26 more
    [ERROR]

**Comment by nokhaizali** [comment]
i also have same issue.  in this site <a href="http://zscarymazegame.com">zscarymazegame.com</a> can anyone solve.

**Comment by mohdaliiqbal** [comment]
that is true, this looks like an errata in the book, the Figure 2-25 shows "clean install" where as the first step asked to do "clean package". They should mention this change when explaining the javadoc:javadoc task. May be wakaleo need to publish this project's read me.

**Comment by wustudybreak** [comment]
Yes. I can confirm what mohdaliiqbal said above worked. All it takes is to change 'clean package' into 'clean install'. No need to change the pom or anything.

**Comment by yxh601** [comment]
when i encounter the problem, the jenkins version is 2.53, while it still exist. Because of the book named Jenkins:The Definitive Guide shows "clean package", so i use it. when i added new build step to running "mvn javadoc:javadoc" , it appeared. Fortunately, i found the comment. Thanks everyone.
